version: '3'

services:
  nginx:
    image: proxy:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80

  frontend:
    image: microblog:latest
    container_name: frontend
    restart: unless-stopped
    expose:
      - 5000

  backend:
    image: microblog:latest
    container_name: backend
    restart: unless-stopped
    expose:
      - 5000
